name: Publish RPMs

on:
  push:
    tags:
      - '*'

env:
  pythonversion: 3.9
  rubyversion: 2.7.2

  # Path to the S3 bucket containing our pre-build packages
  s3root: s3://redismodules/redis-stack

  # Name of the s3 bucket within the account, used to publish our feeds
  # eg: redismodules
  s3publicreponame: packages.redis.io

jobs:

  bulleye-x86:
    uses: ./.github/workflows/RELEASE_REUSE.yml
    with:
      osnick: bulleye
      s3root: ${env.s3root}
      s3publicreponame: ${env.s3publicreponame}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      PACKAGES_AWS_ACCESS_KEY_ID: ${{secrets.PACKAGES_AWS_ACCESS_KEY_ID}}
      PACKAGES_AWS_SECRET_ACCESS_KEY: ${{secrets.PACKAGES_AWS_SECRET_ACCESS_KEY}}
      GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
      GPG_KEY: ${{secrets.GPG_KEY}}


  xenial-x86:
    uses: ./.github/workflows/RELEASE_REUSE.yml
    with:
      osnick: xenial
      s3root: ${env.s3root}
      s3publicreponame: ${env.s3publicreponame}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      PACKAGES_AWS_ACCESS_KEY_ID: ${{secrets.PACKAGES_AWS_ACCESS_KEY_ID}}
      PACKAGES_AWS_SECRET_ACCESS_KEY: ${{secrets.PACKAGES_AWS_SECRET_ACCESS_KEY}}
      GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
      GPG_KEY: ${{secrets.GPG_KEY}}

  bionic-x86:
    uses: ./.github/workflows/RELEASE_REUSE.yml
    with:
      osnick: bionic
      s3root: ${env.s3root}
      s3publicreponame: ${env.s3publicreponame}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      PACKAGES_AWS_ACCESS_KEY_ID: ${{secrets.PACKAGES_AWS_ACCESS_KEY_ID}}
      PACKAGES_AWS_SECRET_ACCESS_KEY: ${{secrets.PACKAGES_AWS_SECRET_ACCESS_KEY}}
      GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
      GPG_KEY: ${{secrets.GPG_KEY}}

  focal-x86:
    uses: ./.github/workflows/RELEASE_REUSE.yml
    with:
      osnick: focal
      s3root: ${env.s3root}
      s3publicreponame: ${env.s3publicreponame}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      PACKAGES_AWS_ACCESS_KEY_ID: ${{secrets.PACKAGES_AWS_ACCESS_KEY_ID}}
      PACKAGES_AWS_SECRET_ACCESS_KEY: ${{secrets.PACKAGES_AWS_SECRET_ACCESS_KEY}}
      GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
      GPG_KEY: ${{secrets.GPG_KEY}}

  bionic-arm64:
    uses: ./.github/workflows/RELEASE_REUSE.yml
    with:
      osnick: bionic
      arch: amd64
      s3root: ${env.s3root}
      s3publicreponame: ${env.s3publicreponame}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      PACKAGES_AWS_ACCESS_KEY_ID: ${{secrets.PACKAGES_AWS_ACCESS_KEY_ID}}
      PACKAGES_AWS_SECRET_ACCESS_KEY: ${{secrets.PACKAGES_AWS_SECRET_ACCESS_KEY}}
      GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
      GPG_KEY: ${{secrets.GPG_KEY}}
